package com.example.celien.drivemycar.utils;


public enum Action {

    SAVE_USER,
    AUTHENTICATE,
    SAVE_CAR,
    MODIFY_CAR,
    LOAD_USER,
    CHECK_USERNAME,
    DELETE_CAR,
    GET_BRAND,
    GET_TRANSACTIONS,
    LOAD_SPECIFIC_CARS,
    SET_ODOMETER,
    SAVE_REQUEST,
    GET_NOTIFS,
    GET_REQUEST_BY_DATE,
    GET_REQUEST_DATA,
    UPDATE_REQUEST_STATE,
    CONFIRM_RENT,
    NOTIFY_SELECTED_ONWER,
    CHECK_TRANSACTION_STATUS,
    COMPUTE_AMOUNT_TO_PAY,
    GET_AGREED_OWNERS,
    REFUTE_RENT,
    LOAD_CARS
}
